version: 2.1
jobs:
  gemfury-collaboration:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run: echo 'export GEMFURY_COLABORATOR="testuser@syngenta.com"' >> "$BASH_ENV"
      - run: brew tap gemfury/tap
      - run: brew install fury-cli
      - run: fury sharing add ${GEMFURY_COLABORATOR} --role=push --account DIEGOGONZALEZ --api-token cRRPJ1Yy6V2veiTNiQG1

workflows:
  gemfury-onboarding:
    jobs:
      - gemfury-collaboration
