version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  gemfury-collaboration:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "setup env variable"
          command: echo 'export GEMFURY_COLABORATOR="testuser@syngenta.com"' >> "$BASH_ENV"
      - run:
          name: "print env variable"
          command: echo ${GEMFURY_COLABORATOR}
      - run:
          name: "print circleci env variables"
          command: echo ${GEMFURY_COLABORATORS}

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  gemfury-onboarding:
    jobs:
      - gemfury-collaboration
