version: 2.1

parameters:
  gemfury_collaborator:
    type: boolean
    default: false

jobs:
  gemfury-collaboration:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: echo 'export GEMFURY_COLABORATOR="testuser@syngenta.com"' >> "$BASH_ENV"

      - run: sudo touch /etc/apt/sources.list.d/fury-cli.list
      - run: sudo sh -c 'echo "deb [trusted=yes] https://apt.fury.io/cli/ * *" >> /etc/apt/sources.list'
      - run: sudo apt-get update
      - run: sudo apt-get install fury-cli
      - run: touch ~/.netrc
      - run: echo -e 'machine api.fury.io \n  login diego.gonzalez-1@syngenta.com \n  password 1Rtoe2-zJbJdWfahFHAf7bbokUPf1HBJo' > ~/.netrc
      - run: fury sharing add ${GEMFURY_COLABORATOR} --role=push --account SYNGENTA-DIGITAL

  test-job:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
workflows:
  test-job:
    jobs:
      - test-job:
          context:
            - test-context
  gemfury-onboarding:
    when: << pipeline.parameters.gemfury_collaborator>>
    jobs:
      - gemfury-collaboration:
          context:
            - test-context
