version: 2.1
jobs:
  gemfury-collaboration:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run: echo 'export GEMFURY_COLABORATOR="testuser@syngenta.com"' >> "$BASH_ENV"
      - run: brew tap gemfury/tap
      - run: brew install fury-cli
      - run: touch ~/.netrc
      - run: echo '"machine api.fury.io \n  login diego.gonzalez-1@syngenta.com \n  password 1Rtoe2-zJbJdWfahFHAf7bbokUPf1HBJo"' > ~/.netrc
      - run: fury sharing add ${GEMFURY_COLABORATOR} --role=push --account SYNGENTA-DIGITAL

workflows:
  gemfury-onboarding:
    jobs:
      - gemfury-collaboration
