version: 2.1
jobs:
  gemfury-collaboration:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run: echo 'export GEMFURY_COLABORATOR="testuser@syngenta.com"' >> "$BASH_ENV"
      - run: sudo touch /etc/apt/sources.list.d/fury-cli.list
      - run: sudo echo "deb [trusted=yes] https://apt.fury.io/cli/ * *" > /etc/apt/sources.list.d/fury-cli.list
      - run: apt-get update
      - run: apt-get install fury-cli
      - run: touch ~/.netrc
      - run: echo -e 'machine api.fury.io \n  login diego.gonzalez-1@syngenta.com \n  password 1Rtoe2-zJbJdWfahFHAf7bbokUPf1HBJo' > ~/.netrc
      - run: fury sharing add ${GEMFURY_COLABORATOR} --role=push --account SYNGENTA-DIGITAL

workflows:
  gemfury-onboarding:
    jobs:
      - gemfury-collaboration
